require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe ClassLevelsController do

  # This should return the minimal set of attributes required to create a valid
  # ClassLevel. As you add validations to ClassLevel, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) { { "character" => "" } }

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # ClassLevelsController. Be sure to keep this updated too.
  let(:valid_session) { {} }

  describe "GET index" do
    it "assigns all class_levels as @class_levels" do
      class_level = ClassLevel.create! valid_attributes
      get :index, {}, valid_session
      assigns(:class_levels).should eq([class_level])
    end
  end

  describe "GET show" do
    it "assigns the requested class_level as @class_level" do
      class_level = ClassLevel.create! valid_attributes
      get :show, {:id => class_level.to_param}, valid_session
      assigns(:class_level).should eq(class_level)
    end
  end

  describe "GET new" do
    it "assigns a new class_level as @class_level" do
      get :new, {}, valid_session
      assigns(:class_level).should be_a_new(ClassLevel)
    end
  end

  describe "GET edit" do
    it "assigns the requested class_level as @class_level" do
      class_level = ClassLevel.create! valid_attributes
      get :edit, {:id => class_level.to_param}, valid_session
      assigns(:class_level).should eq(class_level)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new ClassLevel" do
        expect {
          post :create, {:class_level => valid_attributes}, valid_session
        }.to change(ClassLevel, :count).by(1)
      end

      it "assigns a newly created class_level as @class_level" do
        post :create, {:class_level => valid_attributes}, valid_session
        assigns(:class_level).should be_a(ClassLevel)
        assigns(:class_level).should be_persisted
      end

      it "redirects to the created class_level" do
        post :create, {:class_level => valid_attributes}, valid_session
        response.should redirect_to(ClassLevel.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved class_level as @class_level" do
        # Trigger the behavior that occurs when invalid params are submitted
        ClassLevel.any_instance.stub(:save).and_return(false)
        post :create, {:class_level => { "character" => "invalid value" }}, valid_session
        assigns(:class_level).should be_a_new(ClassLevel)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        ClassLevel.any_instance.stub(:save).and_return(false)
        post :create, {:class_level => { "character" => "invalid value" }}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested class_level" do
        class_level = ClassLevel.create! valid_attributes
        # Assuming there are no other class_levels in the database, this
        # specifies that the ClassLevel created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        ClassLevel.any_instance.should_receive(:update).with({ "character" => "" })
        put :update, {:id => class_level.to_param, :class_level => { "character" => "" }}, valid_session
      end

      it "assigns the requested class_level as @class_level" do
        class_level = ClassLevel.create! valid_attributes
        put :update, {:id => class_level.to_param, :class_level => valid_attributes}, valid_session
        assigns(:class_level).should eq(class_level)
      end

      it "redirects to the class_level" do
        class_level = ClassLevel.create! valid_attributes
        put :update, {:id => class_level.to_param, :class_level => valid_attributes}, valid_session
        response.should redirect_to(class_level)
      end
    end

    describe "with invalid params" do
      it "assigns the class_level as @class_level" do
        class_level = ClassLevel.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        ClassLevel.any_instance.stub(:save).and_return(false)
        put :update, {:id => class_level.to_param, :class_level => { "character" => "invalid value" }}, valid_session
        assigns(:class_level).should eq(class_level)
      end

      it "re-renders the 'edit' template" do
        class_level = ClassLevel.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        ClassLevel.any_instance.stub(:save).and_return(false)
        put :update, {:id => class_level.to_param, :class_level => { "character" => "invalid value" }}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested class_level" do
      class_level = ClassLevel.create! valid_attributes
      expect {
        delete :destroy, {:id => class_level.to_param}, valid_session
      }.to change(ClassLevel, :count).by(-1)
    end

    it "redirects to the class_levels list" do
      class_level = ClassLevel.create! valid_attributes
      delete :destroy, {:id => class_level.to_param}, valid_session
      response.should redirect_to(class_levels_url)
    end
  end

end
