require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe ClassSkillsController do

  # This should return the minimal set of attributes required to create a valid
  # ClassSkill. As you add validations to ClassSkill, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) { { "character_class" => "" } }

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # ClassSkillsController. Be sure to keep this updated too.
  let(:valid_session) { {} }

  describe "GET index" do
    it "assigns all class_skills as @class_skills" do
      class_skill = ClassSkill.create! valid_attributes
      get :index, {}, valid_session
      assigns(:class_skills).should eq([class_skill])
    end
  end

  describe "GET show" do
    it "assigns the requested class_skill as @class_skill" do
      class_skill = ClassSkill.create! valid_attributes
      get :show, {:id => class_skill.to_param}, valid_session
      assigns(:class_skill).should eq(class_skill)
    end
  end

  describe "GET new" do
    it "assigns a new class_skill as @class_skill" do
      get :new, {}, valid_session
      assigns(:class_skill).should be_a_new(ClassSkill)
    end
  end

  describe "GET edit" do
    it "assigns the requested class_skill as @class_skill" do
      class_skill = ClassSkill.create! valid_attributes
      get :edit, {:id => class_skill.to_param}, valid_session
      assigns(:class_skill).should eq(class_skill)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new ClassSkill" do
        expect {
          post :create, {:class_skill => valid_attributes}, valid_session
        }.to change(ClassSkill, :count).by(1)
      end

      it "assigns a newly created class_skill as @class_skill" do
        post :create, {:class_skill => valid_attributes}, valid_session
        assigns(:class_skill).should be_a(ClassSkill)
        assigns(:class_skill).should be_persisted
      end

      it "redirects to the created class_skill" do
        post :create, {:class_skill => valid_attributes}, valid_session
        response.should redirect_to(ClassSkill.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved class_skill as @class_skill" do
        # Trigger the behavior that occurs when invalid params are submitted
        ClassSkill.any_instance.stub(:save).and_return(false)
        post :create, {:class_skill => { "character_class" => "invalid value" }}, valid_session
        assigns(:class_skill).should be_a_new(ClassSkill)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        ClassSkill.any_instance.stub(:save).and_return(false)
        post :create, {:class_skill => { "character_class" => "invalid value" }}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested class_skill" do
        class_skill = ClassSkill.create! valid_attributes
        # Assuming there are no other class_skills in the database, this
        # specifies that the ClassSkill created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        ClassSkill.any_instance.should_receive(:update).with({ "character_class" => "" })
        put :update, {:id => class_skill.to_param, :class_skill => { "character_class" => "" }}, valid_session
      end

      it "assigns the requested class_skill as @class_skill" do
        class_skill = ClassSkill.create! valid_attributes
        put :update, {:id => class_skill.to_param, :class_skill => valid_attributes}, valid_session
        assigns(:class_skill).should eq(class_skill)
      end

      it "redirects to the class_skill" do
        class_skill = ClassSkill.create! valid_attributes
        put :update, {:id => class_skill.to_param, :class_skill => valid_attributes}, valid_session
        response.should redirect_to(class_skill)
      end
    end

    describe "with invalid params" do
      it "assigns the class_skill as @class_skill" do
        class_skill = ClassSkill.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        ClassSkill.any_instance.stub(:save).and_return(false)
        put :update, {:id => class_skill.to_param, :class_skill => { "character_class" => "invalid value" }}, valid_session
        assigns(:class_skill).should eq(class_skill)
      end

      it "re-renders the 'edit' template" do
        class_skill = ClassSkill.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        ClassSkill.any_instance.stub(:save).and_return(false)
        put :update, {:id => class_skill.to_param, :class_skill => { "character_class" => "invalid value" }}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested class_skill" do
      class_skill = ClassSkill.create! valid_attributes
      expect {
        delete :destroy, {:id => class_skill.to_param}, valid_session
      }.to change(ClassSkill, :count).by(-1)
    end

    it "redirects to the class_skills list" do
      class_skill = ClassSkill.create! valid_attributes
      delete :destroy, {:id => class_skill.to_param}, valid_session
      response.should redirect_to(class_skills_url)
    end
  end

end
