require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe ConsumableItemsController do

  # This should return the minimal set of attributes required to create a valid
  # ConsumableItem. As you add validations to ConsumableItem, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) { { "name" => "MyString" } }

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # ConsumableItemsController. Be sure to keep this updated too.
  let(:valid_session) { {} }

  describe "GET index" do
    it "assigns all consumable_items as @consumable_items" do
      consumable_item = ConsumableItem.create! valid_attributes
      get :index, {}, valid_session
      assigns(:consumable_items).should eq([consumable_item])
    end
  end

  describe "GET show" do
    it "assigns the requested consumable_item as @consumable_item" do
      consumable_item = ConsumableItem.create! valid_attributes
      get :show, {:id => consumable_item.to_param}, valid_session
      assigns(:consumable_item).should eq(consumable_item)
    end
  end

  describe "GET new" do
    it "assigns a new consumable_item as @consumable_item" do
      get :new, {}, valid_session
      assigns(:consumable_item).should be_a_new(ConsumableItem)
    end
  end

  describe "GET edit" do
    it "assigns the requested consumable_item as @consumable_item" do
      consumable_item = ConsumableItem.create! valid_attributes
      get :edit, {:id => consumable_item.to_param}, valid_session
      assigns(:consumable_item).should eq(consumable_item)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new ConsumableItem" do
        expect {
          post :create, {:consumable_item => valid_attributes}, valid_session
        }.to change(ConsumableItem, :count).by(1)
      end

      it "assigns a newly created consumable_item as @consumable_item" do
        post :create, {:consumable_item => valid_attributes}, valid_session
        assigns(:consumable_item).should be_a(ConsumableItem)
        assigns(:consumable_item).should be_persisted
      end

      it "redirects to the created consumable_item" do
        post :create, {:consumable_item => valid_attributes}, valid_session
        response.should redirect_to(ConsumableItem.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved consumable_item as @consumable_item" do
        # Trigger the behavior that occurs when invalid params are submitted
        ConsumableItem.any_instance.stub(:save).and_return(false)
        post :create, {:consumable_item => { "name" => "invalid value" }}, valid_session
        assigns(:consumable_item).should be_a_new(ConsumableItem)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        ConsumableItem.any_instance.stub(:save).and_return(false)
        post :create, {:consumable_item => { "name" => "invalid value" }}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested consumable_item" do
        consumable_item = ConsumableItem.create! valid_attributes
        # Assuming there are no other consumable_items in the database, this
        # specifies that the ConsumableItem created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        ConsumableItem.any_instance.should_receive(:update).with({ "name" => "MyString" })
        put :update, {:id => consumable_item.to_param, :consumable_item => { "name" => "MyString" }}, valid_session
      end

      it "assigns the requested consumable_item as @consumable_item" do
        consumable_item = ConsumableItem.create! valid_attributes
        put :update, {:id => consumable_item.to_param, :consumable_item => valid_attributes}, valid_session
        assigns(:consumable_item).should eq(consumable_item)
      end

      it "redirects to the consumable_item" do
        consumable_item = ConsumableItem.create! valid_attributes
        put :update, {:id => consumable_item.to_param, :consumable_item => valid_attributes}, valid_session
        response.should redirect_to(consumable_item)
      end
    end

    describe "with invalid params" do
      it "assigns the consumable_item as @consumable_item" do
        consumable_item = ConsumableItem.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        ConsumableItem.any_instance.stub(:save).and_return(false)
        put :update, {:id => consumable_item.to_param, :consumable_item => { "name" => "invalid value" }}, valid_session
        assigns(:consumable_item).should eq(consumable_item)
      end

      it "re-renders the 'edit' template" do
        consumable_item = ConsumableItem.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        ConsumableItem.any_instance.stub(:save).and_return(false)
        put :update, {:id => consumable_item.to_param, :consumable_item => { "name" => "invalid value" }}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested consumable_item" do
      consumable_item = ConsumableItem.create! valid_attributes
      expect {
        delete :destroy, {:id => consumable_item.to_param}, valid_session
      }.to change(ConsumableItem, :count).by(-1)
    end

    it "redirects to the consumable_items list" do
      consumable_item = ConsumableItem.create! valid_attributes
      delete :destroy, {:id => consumable_item.to_param}, valid_session
      response.should redirect_to(consumable_items_url)
    end
  end

end
