require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe SpellSubSchoolsController do

  # This should return the minimal set of attributes required to create a valid
  # SpellSubSchool. As you add validations to SpellSubSchool, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) { { "name" => "MyString" } }

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # SpellSubSchoolsController. Be sure to keep this updated too.
  let(:valid_session) { {} }

  describe "GET index" do
    it "assigns all spell_sub_schools as @spell_sub_schools" do
      spell_sub_school = SpellSubSchool.create! valid_attributes
      get :index, {}, valid_session
      assigns(:spell_sub_schools).should eq([spell_sub_school])
    end
  end

  describe "GET show" do
    it "assigns the requested spell_sub_school as @spell_sub_school" do
      spell_sub_school = SpellSubSchool.create! valid_attributes
      get :show, {:id => spell_sub_school.to_param}, valid_session
      assigns(:spell_sub_school).should eq(spell_sub_school)
    end
  end

  describe "GET new" do
    it "assigns a new spell_sub_school as @spell_sub_school" do
      get :new, {}, valid_session
      assigns(:spell_sub_school).should be_a_new(SpellSubSchool)
    end
  end

  describe "GET edit" do
    it "assigns the requested spell_sub_school as @spell_sub_school" do
      spell_sub_school = SpellSubSchool.create! valid_attributes
      get :edit, {:id => spell_sub_school.to_param}, valid_session
      assigns(:spell_sub_school).should eq(spell_sub_school)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new SpellSubSchool" do
        expect {
          post :create, {:spell_sub_school => valid_attributes}, valid_session
        }.to change(SpellSubSchool, :count).by(1)
      end

      it "assigns a newly created spell_sub_school as @spell_sub_school" do
        post :create, {:spell_sub_school => valid_attributes}, valid_session
        assigns(:spell_sub_school).should be_a(SpellSubSchool)
        assigns(:spell_sub_school).should be_persisted
      end

      it "redirects to the created spell_sub_school" do
        post :create, {:spell_sub_school => valid_attributes}, valid_session
        response.should redirect_to(SpellSubSchool.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved spell_sub_school as @spell_sub_school" do
        # Trigger the behavior that occurs when invalid params are submitted
        SpellSubSchool.any_instance.stub(:save).and_return(false)
        post :create, {:spell_sub_school => { "name" => "invalid value" }}, valid_session
        assigns(:spell_sub_school).should be_a_new(SpellSubSchool)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        SpellSubSchool.any_instance.stub(:save).and_return(false)
        post :create, {:spell_sub_school => { "name" => "invalid value" }}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested spell_sub_school" do
        spell_sub_school = SpellSubSchool.create! valid_attributes
        # Assuming there are no other spell_sub_schools in the database, this
        # specifies that the SpellSubSchool created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        SpellSubSchool.any_instance.should_receive(:update).with({ "name" => "MyString" })
        put :update, {:id => spell_sub_school.to_param, :spell_sub_school => { "name" => "MyString" }}, valid_session
      end

      it "assigns the requested spell_sub_school as @spell_sub_school" do
        spell_sub_school = SpellSubSchool.create! valid_attributes
        put :update, {:id => spell_sub_school.to_param, :spell_sub_school => valid_attributes}, valid_session
        assigns(:spell_sub_school).should eq(spell_sub_school)
      end

      it "redirects to the spell_sub_school" do
        spell_sub_school = SpellSubSchool.create! valid_attributes
        put :update, {:id => spell_sub_school.to_param, :spell_sub_school => valid_attributes}, valid_session
        response.should redirect_to(spell_sub_school)
      end
    end

    describe "with invalid params" do
      it "assigns the spell_sub_school as @spell_sub_school" do
        spell_sub_school = SpellSubSchool.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        SpellSubSchool.any_instance.stub(:save).and_return(false)
        put :update, {:id => spell_sub_school.to_param, :spell_sub_school => { "name" => "invalid value" }}, valid_session
        assigns(:spell_sub_school).should eq(spell_sub_school)
      end

      it "re-renders the 'edit' template" do
        spell_sub_school = SpellSubSchool.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        SpellSubSchool.any_instance.stub(:save).and_return(false)
        put :update, {:id => spell_sub_school.to_param, :spell_sub_school => { "name" => "invalid value" }}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested spell_sub_school" do
      spell_sub_school = SpellSubSchool.create! valid_attributes
      expect {
        delete :destroy, {:id => spell_sub_school.to_param}, valid_session
      }.to change(SpellSubSchool, :count).by(-1)
    end

    it "redirects to the spell_sub_schools list" do
      spell_sub_school = SpellSubSchool.create! valid_attributes
      delete :destroy, {:id => spell_sub_school.to_param}, valid_session
      response.should redirect_to(spell_sub_schools_url)
    end
  end

end
